version: "3"

services:
  app:
    image: workspace-container:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../:/workspace
    network_mode: host
    command: tail -f /dev/null
